### PR TITLE
Legobug fix

### PR DESCRIPTION
**Pull request by FGDATA**
@JWocky 

This pull request is not necessarily intended for merging. Instead it is intended for a revision.
@legoboyvdlp reported that the Workshop and the Pegasus do not show in the fglauncher (classical version)

I verified this bug. 

I also found that is is correctable by changing 
<PropertyList> line at the beginning of the XMLs
Also, the rating is "alpha" not "Alpha".

The change in the propertly list in the set probably causes some important "Interface" from the JPack not to load, so this fix requires your attention directly.

Currently, temporarily working code is host in the legobug-fix branch (FGMEMBERs) repository until you can revise and incorporate adequately

Thanks
IH-COL

### CODE REVIEW

**Comment by FGDATA** [comment]
legobug2

**Comment by JWocky** [comment]
Wow, does that change just delete the Voodoomaster and Skynet interface? No pushback, not Migraine mode anymore? No ground steering selector for those who don't have pedals but a yoke or can't use their feet anymore?
I know, a lot of this stuff needs more work and is not done yet, but a chop axe to make things happen only because the launcher has a bug? Can we reject this fix and look for another solution?

**Comment by JWocky** [comment]
Your splash is okay, the "alpha" instead of "Alpha" is okay, but he 
can't just kill the interface include. Behind this, there is 
initialization for all SYS6, SYS7 or SYS8 autopilots (aside of the 767 
about a dozen or so other planes). Many use already the pushback from 
Voodoomaster (also available by this interface.xml). SkyNet, and I want 
to make this running in some far future, hangs on it as well. So just 
cutting it out doesn't help. Especially not, because the launcher being 
unable the line with the include clause is an error on the launcher's 
side, not the plane's side.
So, how can we reject this or find another solution?

**Comment by FGDATA** [comment]
Yes. Please do not merge.
I am just reporting a problem. Not a solution! :)

**Comment by FGDATA** [comment]
To reject
(use the Close red button below!)

**Pull request closed without merging**
